/* This javascript file contains (readonly) variables
 * Change this file if you need to add/change error messsage, list etc.
 *
 */

//PI person contacts
var PIList = {	
    "Anders Krogh" : { 
	"BillTo" : "Anders Krogh",
	"Email" : "krogh @ binf.ku.dk",
	"EAN" : "5798000422476",
	"Faculty" : "naturvidenskab",
	"Institute" : "Biologi",
	"Department" : "Bioinformatik // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Anders Lund" : {
	"BillTo" : "Diana Goetz // Anders Lund",
	"Email" : "Anders.Lund @ bric.ku.dk",
	"EAN" : "5798000422834",
	"Faculty" : "BRIC",
	"Institute" : "BRIC",
	"Department" : "BRIC // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Albin Sandelin" : {
	"BillTo" : "Albin Sandelin",
	"Email" : "albin @ binf.ku.dk",
	"EAN" : "5798000422476",
	"Faculty" : "naturvidenskab",
	"Institute" : "Biologi",
	"Department" : "Bioinformatik // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Bo Porse" : {
	"BillTo" : "Diana Goetz // Bo Porse",
	"Email" : "bo.porse @ bric.ku.dk",
	"EAN" : "5798000422834",
	"Faculty" : "BRIC",
	"Institute" : "BRIC",
	"Department" : "BRIC // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Claus Soerensen" : {
	"BillTo" : "Diana Goetz // Claus Soerensen",
	"Email" : "Claus.storgaard @ bric.ku.dk",
	"EAN" : "5798000422834",
	"Faculty" : "BRIC",
	"Institute" : "BRIC",
	"Department" : "BRIC // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Eske Willerslev" : {
	"BillTo" : "Eske Willerslev",
	"Email" : "ewillerslev @ snm.ku.dk",
	"EAN" : "5798000418004",
	"Faculty" : "SCIENCE",
	"Institute" : "Natural History Museum",
	"Department" : "Centre for Geogenetics // Oester Voldgade 5-7 // 1350 Kbh K"
    },
    "Jeppe Vinther" : {
	"BillTo" : "Jeppe Vinther",
	"Email" : "jvinther @ bio.ku.dk",
	"EAN" : "5798000422476",
	"Faculty" : "naturvidenskab",
	"Institute" : "Biologi",
	"Department" : "Bioinformatik // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Jette Lange" : {
	"BillTo" : "Jette Lange",
	"Email" : "bornholdt@binf.ku.dk",
	"EAN" : "5798000422476",
	"Faculty" : "naturvidenskab",
	"Institute" : "Biologi",
	"Department" : "Bioinformatik // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Kristian Helin" : {
	"BillTo" : "Diana Goetz // Kristian Helin",
	"Email" : "Kristian.Helin @ bric.ku.dk",
	"EAN" : "5798000422834",
	"Faculty" : "BRIC",
	"Institute" : "BRIC",
	"Department" : "BRIC // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Kurt Kjaer" : {
	"BillTo" : "Kurt Kjaer",
	"Email" : "kurtk @ snm.ku.dk",
	"EAN" : "5798000418004",
	"Faculty" : "SCIENCE",
	"Institute" : "Natural History Museum",
	"Department" : "Centre for Geogenetics // Oester Voldgade 5-7 // 1350 Kbh K"
    },
    "Klaus Hansen" : {
	"BillTo" : "Diana Goetz // Klaus Hansen",
	"Email" : "Klaus.Hansen @ bric.ku.dk",
	"EAN" : "5798000422834",
	"Faculty" : "BRIC",
	"Institute" : "BRIC",
	"Department" : "BRIC // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Ludovic Orlando" : {
	"BillTo" : "Ludovic Orlando",
	"Email" : "lorlando @ snm.ku.dk",
	"EAN" : "5798000418004",
	"Faculty" : "SCIENCE",
	"Institute" : "Natural History Museum",
	"Department" : "Centre for Geogenetics // Oester Voldgade 5-7 // 1350 Kbh K"
    },
    "Morten Froedin": {
	"BillTo" : "Diana Goetz // Morten Froedin",
	"Email" : "Morten.Frodin @ bric.ku.dk",
	"EAN" : "5798000422834",
	"Faculty" : "BRIC",
	"Institute" : "BRIC",
	"Department" : "BRIC // Ole Maaloes Vej 5 // 2200 Kbh N"
    },
    "Soeren Soerensen" : {
	"BillTo" : "Soeren Soerensen",
	"Email" : "sjs @ bio.ku.dk",
	"EAN" : "57980000418028",
	"Faculty" : "Nat",
	"Institute" : "Biologi",
	"Department" : "Molecular Microbial Ecology Group // Universitetsparken 15 // 2100 Kbh OE"
    },
    "Tom Gilbert" : {
	"BillTo" : "Tom Gilbert",
	"Email" : "tgilbert @ snm.ku.dk",
	"EAN" : "5798000418004",
	"Faculty" : "SCIENCE",
	"Institute" : "Natural History Museum",
	"Department" : "Centre for Geogenetics // Oester Voldgade 5-7 // 1350 Kbh K"
    },
    "other" : {
	"BillTo" : "",
	"Email" : "",
	"EAN" : "",
	"Faculty" : "",
	"Institute" : "",
	"Department" : ""
    }
};
	
	var tubeTagList = {	
		"Anders Krogh" : "ANK",
		"Anders Lund" : "ANL",
		"Albin Sandelin" : "ALS",
		"Bo Porse" : "BOP",
		"Claus Soerensen" : "CLS",
		"Eske Willerslev" : "ESW",
		"Jeppe Vinther" : "JEV",
		"Kristian Helin" : "KRH",
		"Kurt Kjaer" : "KUK",
		"Klaus Hansen" : "KLH",
		"Ludovic Orlando" : "LUO",
		"Morten Froedin" : "MOF",
		"Soeren Soerensen" : "SOS",
		"Tom Gilbert" : "TOG"
	};
	
//Table variables:
	var concentrationMin = 0.5; 
	var concentrationMax = 100;
	var AverageLibInsMin = 20; 
	var AverageLibInsMax = 650;
	
	//Add runtype min and max
	var runtypeMin = 1;
	var runtypeMax = 32;

//Table class names
	var tubeTagClassname = "tubeTag";
	var sampleIdClassname = "sampleId";
	var concentrationClassname = "concentration";
	var averageLibClassname = "aveLibIns";
	var indexSeqClassname = "indexSeq";
	var indexNameClassname = "indexName";
	var projectNameClassname = "ProjectName";
	
	var refGenomeClassname = "refgenome";
	var spicesClassname = "species";
	var cellTypeClassname = "CellType";
	var ipClassname = "IP";
	var TOEClassname = "TOE";

	// List of known index sequences
	$indexSequenceList = [
	    {"label":"ATCACG", "id":"Index_1"},
	    {"label":"CGATGT", "id":"Index_2"},
	    {"label":"TTAGGC", "id":"Index_3"},
	    {"label":"TGACCA", "id":"Index_4"},
	    {"label":"ACAGTG", "id":"Index_5"},
	    {"label":"GCCAAT", "id":"Index_6"},
	    {"label":"CAGATC", "id":"Index_7"},
	    {"label":"ACTTGA", "id":"Index_8"},
	    {"label":"GATCAG", "id":"Index_9"},
	    {"label":"TAGCTT", "id":"Index_10"},
	    {"label":"GGCTAC", "id":"Index_11"},
	    {"label":"CTTGTA", "id":"Index_12"},
	    {"label":"CGTAGT", "id":"Cap_index_1"},
	    {"label":"CAGCAC", "id":"Cap_index_2"},
	    {"label":"ACTGCG", "id":"Cap_index_3"},
	    {"label":"TCGATG", "id":"Cap_index_4"},
	    {"label":"TACGAG", "id":"Cap_index_5"},
	    {"label":"GTCGTC", "id":"Cap_index_6"},
	    {"label":"GCTACT", "id":"Cap_index_7"},
	    {"label":"GAGTAG", "id":"Cap_index_8"},
	    {"label":"AGTGAG", "id":"Cap_index_9"},
	    {"label":"ACAGAG", "id":"Cap_index_10"},
	    {"label":"CTCTGC", "id":"Cap_index_11"},
	    {"label":"TAGCTG", "id":"Cap_index_12"},
	    {"label":"CTATCA", "id":"Custom_13"},
	    {"label":"CGTATA", "id":"Custom_14"},
	    {"label":"TGATCG", "id":"Custom_15"},
	    {"label":"GTGTAT", "id":"Custom_16"},
	    {"label":"CGCTAT", "id":"Custom_17"},
	    {"label":"TGAACA", "id":"Custom_18"},
	    {"label":"GTATCT", "id":"Custom_19"},
	    {"label":"CAGCTA", "id":"Custom_20"},
	    {"label":"ACATAC", "id":"Custom_21"},
	    {"label":"TGAGCC", "id":"Custom_22"},
	    {"label":"AGCATG", "id":"Custom_23"},
	    {"label":"CGATGA", "id":"Custom_24"},
	    {"label":"TAGATG", "id":"Custom_25"},
	    {"label":"TGTGAC", "id":"Custom_26"},
	    {"label":"TGCATA", "id":"Custom_27"},
	    {"label":"TCTCGC", "id":"Custom_28"},
	    {"label":"TGATGC", "id":"Custom_29"},
	    {"label":"GACGAC", "id":"Custom_30"},
	    {"label":"GACACT", "id":"Custom_31"},
	    {"label":"ACGCAT", "id":"Custom_32"},
	    {"label":"GACCGG", "id":"Custom_33"},
	    {"label":"GAGATA", "id":"Custom_34"},
	    {"label":"CTGACA", "id":"Custom_35"},
	    {"label":"TGCAGG", "id":"Custom_36"},
	    {"label":"ACTGCC", "id":"Custom_37"},
	    {"label":"GCAACG", "id":"Custom_38"},
	    {"label":"CGACCT", "id":"Custom_39"},
	    {"label":"TGACGT", "id":"Custom_40"},
	    {"label":"TGTCTG", "id":"Custom_41"},
	    {"label":"ACGTGC", "id":"Custom_42"},
	    {"label":"TGATCC", "id":"Custom_43"},
	    {"label":"CTCTAG", "id":"Custom_44"},
	    {"label":"GAGAAG", "id":"Custom_45"},
	    {"label":"CACGAA", "id":"Custom_46"},
	    {"label":"CATAGA", "id":"Custom_47"},
	    {"label":"ACAGTC", "id":"Custom_48"},
	    {"label":"CATCGT", "id":"Custom_49"},
	    {"label":"TTGAAC", "id":"Custom_50"},
	    {"label":"ACGTCG", "id":"Custom_51"},
	    {"label":"ATCACG", "id":"TruSeq_1"},
	    {"label":"CGATGT", "id":"TruSeq_2"},
	    {"label":"TTAGGC", "id":"TruSeq_3"},
	    {"label":"TGACCA", "id":"TruSeq_4"},
	    {"label":"ACAGTG", "id":"TruSeq_5"},
	    {"label":"GCCAAT", "id":"TruSeq_6"},
	    {"label":"CAGATC", "id":"TruSeq_7"},
	    {"label":"ACTTGA", "id":"TruSeq_8"},
	    {"label":"GATCAG", "id":"TruSeq_9"},
	    {"label":"TAGCTT", "id":"TruSeq_10"},
	    {"label":"GGCTAC", "id":"TruSeq_11"},
	    {"label":"CTTGTA", "id":"TruSeq_12"},
	    {"label":"AGTCAA", "id":"TruSeq_13"},
	    {"label":"AGTTCC", "id":"TruSeq_14"},
	    {"label":"ATGTCA", "id":"TruSeq_15"},
	    {"label":"CCGTCC", "id":"TruSeq_16"},
	    {"label":"GTAGAG", "id":"TruSeq_17"},
	    {"label":"GTCCGC", "id":"TruSeq_18"},
	    {"label":"GTGAAA", "id":"TruSeq_19"},
	    {"label":"GTGGCC", "id":"TruSeq_20"},
	    {"label":"GTTTCG", "id":"TruSeq_21"},
	    {"label":"CGTACG", "id":"TruSeq_22"},
	    {"label":"GAGTGG", "id":"TruSeq_23"},
	    {"label":"GGTAGC", "id":"TruSeq_24"},
	    {"label":"ACTGAT", "id":"TruSeq_25"},
	    {"label":"ATGAGC", "id":"TruSeq_26"},
	    {"label":"ATTCCT", "id":"TruSeq_27"},
	    {"label":"CAAAAG", "id":"TruSeq_28"},
	    {"label":"CAACTA", "id":"TruSeq_29"},
	    {"label":"CACCGG", "id":"TruSeq_30"},
	    {"label":"CACGAT", "id":"TruSeq_31"},
	    {"label":"CACTCA", "id":"TruSeq_32"},
	    {"label":"CAGGCG", "id":"TruSeq_33"},
	    {"label":"CATGGC", "id":"TruSeq_34"},
	    {"label":"CATTTT", "id":"TruSeq_35"},
	    {"label":"CCAACA", "id":"TruSeq_36"},
	    {"label":"CGGAAT", "id":"TruSeq_37"},
	    {"label":"CTAGCT", "id":"TruSeq_38"},
	    {"label":"CTATAC", "id":"TruSeq_39"},
	    {"label":"CTCAGA", "id":"TruSeq_40"},
	    {"label":"GACGAC", "id":"TruSeq_41"},
	    {"label":"TAATCG", "id":"TruSeq_42"},
	    {"label":"TACAGC", "id":"TruSeq_43"},
	    {"label":"TATAAT", "id":"TruSeq_44"},
	    {"label":"TCATTC", "id":"TruSeq_45"},
	    {"label":"TCCCGA", "id":"TruSeq_46"},
	    {"label":"TCGAAG", "id":"TruSeq_47"},
	    {"label":"TCGGCA", "id":"TruSeq_48"},
	    {"label":"ATCACG", "id":"NEBNext_1"},
	    {"label":"CGATGT", "id":"NEBNext_2"},
	    {"label":"TTAGGC", "id":"NEBNext_3"},
	    {"label":"TGACCA", "id":"NEBNext_4"},
	    {"label":"ACAGTG", "id":"NEBNext_5"},
	    {"label":"GCCAAT", "id":"NEBNext_6"},
	    {"label":"CAGATC", "id":"NEBNext_7"},
	    {"label":"ACTTGA", "id":"NEBNext_8"},
	    {"label":"GATCAG", "id":"NEBNext_9"},
	    {"label":"TAGCTT", "id":"NEBNext_10"},
	    {"label":"GGCTAC", "id":"NEBNext_11"},
	    {"label":"CTTGTA", "id":"NEBNext_12"},
	    {"label":"ATCACG", "id":"AD001"},
	    {"label":"CGATGT", "id":"AD002"},
	    {"label":"TTAGGC", "id":"AD003"},
	    {"label":"TGACCA", "id":"AD004"},
	    {"label":"ACAGTG", "id":"AD005"},
	    {"label":"GCCAAT", "id":"AD006"},
	    {"label":"CAGATC", "id":"AD007"},
	    {"label":"ACTTGA", "id":"AD008"},
	    {"label":"GATCAG", "id":"AD009"},
	    {"label":"TAGCTT", "id":"AD010"},
	    {"label":"GGCTAC", "id":"AD011"},
	    {"label":"CTTGTA", "id":"AD012"},
	    {"label":"AGTCAA", "id":"AD013"},
	    {"label":"AGTTCC", "id":"AD014"},
	    {"label":"ATGTCA", "id":"AD015"},
	    {"label":"CCGTCC", "id":"AD016"},
	    {"label":"GTCCGC", "id":"AD018"},
	    {"label":"GTGAAA", "id":"AD019"},
	    {"label":"GTGGCC", "id":"AD020"},
	    {"label":"GTTTCG", "id":"AD021"},
	    {"label":"CGTACG", "id":"AD022"},
	    {"label":"GAGTGG", "id":"AD023"},
	    {"label":"ACTGAT", "id":"AD025"},
	    {"label":"ATTCCT", "id":"AD027"},
	    {"label":"TCATCG", "id":"Custom_24rev"},
	    {"label":"ACGTCA", "id":"Custom_40rev"},
	    {"label":"CAGGCC", "id":"SB_33"},
	    {"label":"AAGGGA", "id":"L2V6DR_BC1"},
	    {"label":"CCTTCA", "id":"L2V6DR_BC2"},
	    {"label":"GGACCC", "id":"L2V6DR_BC3"},
	    {"label":"TTCAGC", "id":"L2V6DR_BC4"},
	    {"label":"TAAGGCGA_TAGATCGC", "id":"N701_S501"},
	    {"label":"TAAGGCGA_CTCTCTAT", "id":"N701_S502"},
	    {"label":"TAAGGCGA_TATCCTCT", "id":"N701_S503"},
	    {"label":"TAAGGCGA_AGAGTAGA", "id":"N701_S504"},
	    {"label":"TAAGGCGA_GTAAGGAG", "id":"N701_S505"},
	    {"label":"TAAGGCGA_ACTGCATA", "id":"N701_S506"},
	    {"label":"TAAGGCGA_AAGGAGTA", "id":"N701_S507"},
	    {"label":"TAAGGCGA_CTAAGCCT", "id":"N701_S508"},
	    {"label":"CGTACTAG_TAGATCGC", "id":"N702_S501"},
	    {"label":"CGTACTAG_CTCTCTAT", "id":"N702_S502"},
	    {"label":"CGTACTAG_TATCCTCT", "id":"N702_S503"},
	    {"label":"CGTACTAG_AGAGTAGA", "id":"N702_S504"},
	    {"label":"CGTACTAG_GTAAGGAG", "id":"N702_S505"},
	    {"label":"CGTACTAG_ACTGCATA", "id":"N702_S506"},
	    {"label":"CGTACTAG_AAGGAGTA", "id":"N702_S507"},
	    {"label":"CGTACTAG_CTAAGCCT", "id":"N702_S508"},
	    {"label":"AGGCAGAA_TAGATCGC", "id":"N703_S501"},
	    {"label":"AGGCAGAA_CTCTCTAT", "id":"N703_S502"},
	    {"label":"AGGCAGAA_TATCCTCT", "id":"N703_S503"},
	    {"label":"AGGCAGAA_AGAGTAGA", "id":"N703_S504"},
	    {"label":"AGGCAGAA_GTAAGGAG", "id":"N703_S505"},
	    {"label":"AGGCAGAA_ACTGCATA", "id":"N703_S506"},
	    {"label":"AGGCAGAA_AAGGAGTA", "id":"N703_S507"},
	    {"label":"AGGCAGAA_CTAAGCCT", "id":"N703_S508"},
	    {"label":"TCCTGAGC_TAGATCGC", "id":"N704_S501"},
	    {"label":"TCCTGAGC_CTCTCTAT", "id":"N704_S502"},
	    {"label":"TCCTGAGC_TATCCTCT", "id":"N704_S503"},
	    {"label":"TCCTGAGC_AGAGTAGA", "id":"N704_S504"},
	    {"label":"TCCTGAGC_GTAAGGAG", "id":"N704_S505"},
	    {"label":"TCCTGAGC_ACTGCATA", "id":"N704_S506"},
	    {"label":"TCCTGAGC_AAGGAGTA", "id":"N704_S507"},
	    {"label":"TCCTGAGC_CTAAGCCT", "id":"N704_S508"},
	    {"label":"GGACTCCT_TAGATCGC", "id":"N705_S501"},
	    {"label":"GGACTCCT_CTCTCTAT", "id":"N705_S502"},
	    {"label":"GGACTCCT_TATCCTCT", "id":"N705_S503"},
	    {"label":"GGACTCCT_AGAGTAGA", "id":"N705_S504"},
	    {"label":"GGACTCCT_GTAAGGAG", "id":"N705_S505"},
	    {"label":"GGACTCCT_ACTGCATA", "id":"N705_S506"},
	    {"label":"GGACTCCT_AAGGAGTA", "id":"N705_S507"},
	    {"label":"GGACTCCT_CTAAGCCT", "id":"N705_S508"},
	    {"label":"TAGGCATG_TAGATCGC", "id":"N706_S501"},
	    {"label":"TAGGCATG_CTCTCTAT", "id":"N706_S502"},
	    {"label":"TAGGCATG_TATCCTCT", "id":"N706_S503"},
	    {"label":"TAGGCATG_AGAGTAGA", "id":"N706_S504"},
	    {"label":"TAGGCATG_GTAAGGAG", "id":"N706_S505"},
	    {"label":"TAGGCATG_ACTGCATA", "id":"N706_S506"},
	    {"label":"TAGGCATG_AAGGAGTA", "id":"N706_S507"},
	    {"label":"TAGGCATG_CTAAGCCT", "id":"N706_S508"},
	    {"label":"CTCTCTAC_TAGATCGC", "id":"N707_S501"},
	    {"label":"CTCTCTAC_CTCTCTAT", "id":"N707_S502"},
	    {"label":"CTCTCTAC_TATCCTCT", "id":"N707_S503"},
	    {"label":"CTCTCTAC_AGAGTAGA", "id":"N707_S504"},
	    {"label":"CTCTCTAC_GTAAGGAG", "id":"N707_S505"},
	    {"label":"CTCTCTAC_ACTGCATA", "id":"N707_S506"},
	    {"label":"CTCTCTAC_AAGGAGTA", "id":"N707_S507"},
	    {"label":"CTCTCTAC_CTAAGCCT", "id":"N707_S508"},
	    {"label":"CAGAGAGG_TAGATCGC", "id":"N708_S501"},
	    {"label":"CAGAGAGG_CTCTCTAT", "id":"N708_S502"},
	    {"label":"CAGAGAGG_TATCCTCT", "id":"N708_S503"},
	    {"label":"CAGAGAGG_AGAGTAGA", "id":"N708_S504"},
	    {"label":"CAGAGAGG_GTAAGGAG", "id":"N708_S505"},
	    {"label":"CAGAGAGG_ACTGCATA", "id":"N708_S506"},
	    {"label":"CAGAGAGG_AAGGAGTA", "id":"N708_S507"},
	    {"label":"CAGAGAGG_CTAAGCCT", "id":"N708_S508"},
	    {"label":"GCTACGCT_TAGATCGC", "id":"N709_S501"},
	    {"label":"GCTACGCT_CTCTCTAT", "id":"N709_S502"},
	    {"label":"GCTACGCT_TATCCTCT", "id":"N709_S503"},
	    {"label":"GCTACGCT_AGAGTAGA", "id":"N709_S504"},
	    {"label":"GCTACGCT_GTAAGGAG", "id":"N709_S505"},
	    {"label":"GCTACGCT_ACTGCATA", "id":"N709_S506"},
	    {"label":"GCTACGCT_AAGGAGTA", "id":"N709_S507"},
	    {"label":"GCTACGCT_CTAAGCCT", "id":"N709_S508"},
	    {"label":"CGAGGCTG_TAGATCGC", "id":"N710_S501"},
	    {"label":"CGAGGCTG_CTCTCTAT", "id":"N710_S502"},
	    {"label":"CGAGGCTG_TATCCTCT", "id":"N710_S503"},
	    {"label":"CGAGGCTG_AGAGTAGA", "id":"N710_S504"},
	    {"label":"CGAGGCTG_GTAAGGAG", "id":"N710_S505"},
	    {"label":"CGAGGCTG_ACTGCATA", "id":"N710_S506"},
	    {"label":"CGAGGCTG_AAGGAGTA", "id":"N710_S507"},
	    {"label":"CGAGGCTG_CTAAGCCT", "id":"N710_S508"},
	    {"label":"AAGAGGCA_TAGATCGC", "id":"N711_S501"},
	    {"label":"AAGAGGCA_CTCTCTAT", "id":"N711_S502"},
	    {"label":"AAGAGGCA_TATCCTCT", "id":"N711_S503"},
	    {"label":"AAGAGGCA_AGAGTAGA", "id":"N711_S504"},
	    {"label":"AAGAGGCA_GTAAGGAG", "id":"N711_S505"},
	    {"label":"AAGAGGCA_ACTGCATA", "id":"N711_S506"},
	    {"label":"AAGAGGCA_AAGGAGTA", "id":"N711_S507"},
	    {"label":"AAGAGGCA_CTAAGCCT", "id":"N711_S508"},
	    {"label":"GTAGAGGA_TAGATCGC", "id":"N712_S501"},
	    {"label":"GTAGAGGA_CTCTCTAT", "id":"N712_S502"},
	    {"label":"GTAGAGGA_TATCCTCT", "id":"N712_S503"},
	    {"label":"GTAGAGGA_AGAGTAGA", "id":"N712_S504"},
	    {"label":"GTAGAGGA_GTAAGGAG", "id":"N712_S505"},
	    {"label":"GTAGAGGA_ACTGCATA", "id":"N712_S506"},
	    {"label":"GTAGAGGA_AAGGAGTA", "id":"N712_S507"},
	    {"label":"GTAGAGGA_CTAAGCCT", "id":"N712_S508"},
	    {"label":"AACCAACG_AACCAACG", "id":"AF1_AR1"},
	    {"label":"AACCAACG_AACCGAAC", "id":"AF1_AR2"},
	    {"label":"AACCAACG_ACTGCTCT", "id":"AF1_AR3"},
	    {"label":"AACCAACG_ATACCAGG", "id":"AF1_AR4"},
	    {"label":"AACCAACG_ATTGATTA", "id":"AF1_AR5"},
	    {"label":"AACCAACG_CAACCTCT", "id":"AF1_AR6"},
	    {"label":"AACCAACG_CAGAATAT", "id":"AF1_AR7"},
	    {"label":"AACCAACG_CCATGCGC", "id":"AF1_AR8"},
	    {"label":"AACCAACG_CCGCTAGG", "id":"AF1_AR9"},
	    {"label":"AACCAACG_CGCATCAT", "id":"AF1_AR10"},
	    {"label":"AACCAACG_GAGGAGTA", "id":"AF1_AR11"},
	    {"label":"AACCAACG_GCTGGTCA", "id":"AF1_AR12"},
	    {"label":"AACCAACG_GGAGGCTC", "id":"AF1_AR13"},
	    {"label":"AACCAACG_GTAAGAAG", "id":"AF1_AR14"},
	    {"label":"AACCAACG_GTTAAGTT", "id":"AF1_AR15"},
	    {"label":"AACCAACG_TCGTTCGA", "id":"AF1_AR16"},
	    {"label":"AACCAACG_TGAATGGC", "id":"AF1_AR17"},
	    {"label":"AACCAACG_TGATCTCA", "id":"AF1_AR18"},
	    {"label":"AACCAACG_TGGTCCTG", "id":"AF1_AR19"},
	    {"label":"AACCAACG_TGGTTGAC", "id":"AF1_AR20"},
	    {"label":"AAGAGCTC_AACCAACG", "id":"AF2_AR1"},
	    {"label":"AAGAGCTC_AACCGAAC", "id":"AF2_AR2"},
	    {"label":"AAGAGCTC_ACTGCTCT", "id":"AF2_AR3"},
	    {"label":"AAGAGCTC_ATACCAGG", "id":"AF2_AR4"},
	    {"label":"AAGAGCTC_ATTGATTA", "id":"AF2_AR5"},
	    {"label":"AAGAGCTC_CAACCTCT", "id":"AF2_AR6"},
	    {"label":"AAGAGCTC_CAGAATAT", "id":"AF2_AR7"},
	    {"label":"AAGAGCTC_CCATGCGC", "id":"AF2_AR8"},
	    {"label":"AAGAGCTC_CCGCTAGG", "id":"AF2_AR9"},
	    {"label":"AAGAGCTC_CGCATCAT", "id":"AF2_AR10"},
	    {"label":"AAGAGCTC_GAGGAGTA", "id":"AF2_AR11"},
	    {"label":"AAGAGCTC_GCTGGTCA", "id":"AF2_AR12"},
	    {"label":"AAGAGCTC_GGAGGCTC", "id":"AF2_AR13"},
	    {"label":"AAGAGCTC_GTAAGAAG", "id":"AF2_AR14"},
	    {"label":"AAGAGCTC_GTTAAGTT", "id":"AF2_AR15"},
	    {"label":"AAGAGCTC_TCGTTCGA", "id":"AF2_AR16"},
	    {"label":"AAGAGCTC_TGAATGGC", "id":"AF2_AR17"},
	    {"label":"AAGAGCTC_TGATCTCA", "id":"AF2_AR18"},
	    {"label":"AAGAGCTC_TGGTCCTG", "id":"AF2_AR19"},
	    {"label":"AAGAGCTC_TGGTTGAC", "id":"AF2_AR20"},
	    {"label":"AGATAAGT_AACCAACG", "id":"AF3_AR1"},
	    {"label":"AGATAAGT_AACCGAAC", "id":"AF3_AR2"},
	    {"label":"AGATAAGT_ACTGCTCT", "id":"AF3_AR3"},
	    {"label":"AGATAAGT_ATACCAGG", "id":"AF3_AR4"},
	    {"label":"AGATAAGT_ATTGATTA", "id":"AF3_AR5"},
	    {"label":"AGATAAGT_CAACCTCT", "id":"AF3_AR6"},
	    {"label":"AGATAAGT_CAGAATAT", "id":"AF3_AR7"},
	    {"label":"AGATAAGT_CCATGCGC", "id":"AF3_AR8"},
	    {"label":"AGATAAGT_CCGCTAGG", "id":"AF3_AR9"},
	    {"label":"AGATAAGT_CGCATCAT", "id":"AF3_AR10"},
	    {"label":"AGATAAGT_GAGGAGTA", "id":"AF3_AR11"},
	    {"label":"AGATAAGT_GCTGGTCA", "id":"AF3_AR12"},
	    {"label":"AGATAAGT_GGAGGCTC", "id":"AF3_AR13"},
	    {"label":"AGATAAGT_GTAAGAAG", "id":"AF3_AR14"},
	    {"label":"AGATAAGT_GTTAAGTT", "id":"AF3_AR15"},
	    {"label":"AGATAAGT_TCGTTCGA", "id":"AF3_AR16"},
	    {"label":"AGATAAGT_TGAATGGC", "id":"AF3_AR17"},
	    {"label":"AGATAAGT_TGATCTCA", "id":"AF3_AR18"},
	    {"label":"AGATAAGT_TGGTCCTG", "id":"AF3_AR19"},
	    {"label":"AGATAAGT_TGGTTGAC", "id":"AF3_AR20"},
	    {"label":"CAACCATC_AACCAACG", "id":"AF4_AR1"},
	    {"label":"CAACCATC_AACCGAAC", "id":"AF4_AR2"},
	    {"label":"CAACCATC_ACTGCTCT", "id":"AF4_AR3"},
	    {"label":"CAACCATC_ATACCAGG", "id":"AF4_AR4"},
	    {"label":"CAACCATC_ATTGATTA", "id":"AF4_AR5"},
	    {"label":"CAACCATC_CAACCTCT", "id":"AF4_AR6"},
	    {"label":"CAACCATC_CAGAATAT", "id":"AF4_AR7"},
	    {"label":"CAACCATC_CCATGCGC", "id":"AF4_AR8"},
	    {"label":"CAACCATC_CCGCTAGG", "id":"AF4_AR9"},
	    {"label":"CAACCATC_CGCATCAT", "id":"AF4_AR10"},
	    {"label":"CAACCATC_GAGGAGTA", "id":"AF4_AR11"},
	    {"label":"CAACCATC_GCTGGTCA", "id":"AF4_AR12"},
	    {"label":"CAACCATC_GGAGGCTC", "id":"AF4_AR13"},
	    {"label":"CAACCATC_GTAAGAAG", "id":"AF4_AR14"},
	    {"label":"CAACCATC_GTTAAGTT", "id":"AF4_AR15"},
	    {"label":"CAACCATC_TCGTTCGA", "id":"AF4_AR16"},
	    {"label":"CAACCATC_TGAATGGC", "id":"AF4_AR17"},
	    {"label":"CAACCATC_TGATCTCA", "id":"AF4_AR18"},
	    {"label":"CAACCATC_TGGTCCTG", "id":"AF4_AR19"},
	    {"label":"CAACCATC_TGGTTGAC", "id":"AF4_AR20"},
	    {"label":"CCTAGCGA_AACCAACG", "id":"AF5_AR1"},
	    {"label":"CCTAGCGA_AACCGAAC", "id":"AF5_AR2"},
	    {"label":"CCTAGCGA_ACTGCTCT", "id":"AF5_AR3"},
	    {"label":"CCTAGCGA_ATACCAGG", "id":"AF5_AR4"},
	    {"label":"CCTAGCGA_ATTGATTA", "id":"AF5_AR5"},
	    {"label":"CCTAGCGA_CAACCTCT", "id":"AF5_AR6"},
	    {"label":"CCTAGCGA_CAGAATAT", "id":"AF5_AR7"},
	    {"label":"CCTAGCGA_CCATGCGC", "id":"AF5_AR8"},
	    {"label":"CCTAGCGA_CCGCTAGG", "id":"AF5_AR9"},
	    {"label":"CCTAGCGA_CGCATCAT", "id":"AF5_AR10"},
	    {"label":"CCTAGCGA_GAGGAGTA", "id":"AF5_AR11"},
	    {"label":"CCTAGCGA_GCTGGTCA", "id":"AF5_AR12"},
	    {"label":"CCTAGCGA_GGAGGCTC", "id":"AF5_AR13"},
	    {"label":"CCTAGCGA_GTAAGAAG", "id":"AF5_AR14"},
	    {"label":"CCTAGCGA_GTTAAGTT", "id":"AF5_AR15"},
	    {"label":"CCTAGCGA_TCGTTCGA", "id":"AF5_AR16"},
	    {"label":"CCTAGCGA_TGAATGGC", "id":"AF5_AR17"},
	    {"label":"CCTAGCGA_TGATCTCA", "id":"AF5_AR18"},
	    {"label":"CCTAGCGA_TGGTCCTG", "id":"AF5_AR19"},
	    {"label":"CCTAGCGA_TGGTTGAC", "id":"AF5_AR20"},
	    {"label":"GCTCTGCT_AACCAACG", "id":"AF6_AR1"},
	    {"label":"GCTCTGCT_AACCGAAC", "id":"AF6_AR2"},
	    {"label":"GCTCTGCT_ACTGCTCT", "id":"AF6_AR3"},
	    {"label":"GCTCTGCT_ATACCAGG", "id":"AF6_AR4"},
	    {"label":"GCTCTGCT_ATTGATTA", "id":"AF6_AR5"},
	    {"label":"GCTCTGCT_CAACCTCT", "id":"AF6_AR6"},
	    {"label":"GCTCTGCT_CAGAATAT", "id":"AF6_AR7"},
	    {"label":"GCTCTGCT_CCATGCGC", "id":"AF6_AR8"},
	    {"label":"GCTCTGCT_CCGCTAGG", "id":"AF6_AR9"},
	    {"label":"GCTCTGCT_CGCATCAT", "id":"AF6_AR10"},
	    {"label":"GCTCTGCT_GAGGAGTA", "id":"AF6_AR11"},
	    {"label":"GCTCTGCT_GCTGGTCA", "id":"AF6_AR12"},
	    {"label":"GCTCTGCT_GGAGGCTC", "id":"AF6_AR13"},
	    {"label":"GCTCTGCT_GTAAGAAG", "id":"AF6_AR14"},
	    {"label":"GCTCTGCT_GTTAAGTT", "id":"AF6_AR15"},
	    {"label":"GCTCTGCT_TCGTTCGA", "id":"AF6_AR16"},
	    {"label":"GCTCTGCT_TGAATGGC", "id":"AF6_AR17"},
	    {"label":"GCTCTGCT_TGATCTCA", "id":"AF6_AR18"},
	    {"label":"GCTCTGCT_TGGTCCTG", "id":"AF6_AR19"},
	    {"label":"GCTCTGCT_TGGTTGAC", "id":"AF6_AR20"},
	    {"label":"GGCGTTGC_AACCAACG", "id":"AF7_AR1"},
	    {"label":"GGCGTTGC_AACCGAAC", "id":"AF7_AR2"},
	    {"label":"GGCGTTGC_ACTGCTCT", "id":"AF7_AR3"},
	    {"label":"GGCGTTGC_ATACCAGG", "id":"AF7_AR4"},
	    {"label":"GGCGTTGC_ATTGATTA", "id":"AF7_AR5"},
	    {"label":"GGCGTTGC_CAACCTCT", "id":"AF7_AR6"},
	    {"label":"GGCGTTGC_CAGAATAT", "id":"AF7_AR7"},
	    {"label":"GGCGTTGC_CCATGCGC", "id":"AF7_AR8"},
	    {"label":"GGCGTTGC_CCGCTAGG", "id":"AF7_AR9"},
	    {"label":"GGCGTTGC_CGCATCAT", "id":"AF7_AR10"},
	    {"label":"GGCGTTGC_GAGGAGTA", "id":"AF7_AR11"},
	    {"label":"GGCGTTGC_GCTGGTCA", "id":"AF7_AR12"},
	    {"label":"GGCGTTGC_GGAGGCTC", "id":"AF7_AR13"},
	    {"label":"GGCGTTGC_GTAAGAAG", "id":"AF7_AR14"},
	    {"label":"GGCGTTGC_GTTAAGTT", "id":"AF7_AR15"},
	    {"label":"GGCGTTGC_TCGTTCGA", "id":"AF7_AR16"},
	    {"label":"GGCGTTGC_TGAATGGC", "id":"AF7_AR17"},
	    {"label":"GGCGTTGC_TGATCTCA", "id":"AF7_AR18"},
	    {"label":"GGCGTTGC_TGGTCCTG", "id":"AF7_AR19"},
	    {"label":"GGCGTTGC_TGGTTGAC", "id":"AF7_AR20"},
	    {"label":"GTCGCTAG_AACCAACG", "id":"AF8_AR1"},
	    {"label":"GTCGCTAG_AACCGAAC", "id":"AF8_AR2"},
	    {"label":"GTCGCTAG_ACTGCTCT", "id":"AF8_AR3"},
	    {"label":"GTCGCTAG_ATACCAGG", "id":"AF8_AR4"},
	    {"label":"GTCGCTAG_ATTGATTA", "id":"AF8_AR5"},
	    {"label":"GTCGCTAG_CAACCTCT", "id":"AF8_AR6"},
	    {"label":"GTCGCTAG_CAGAATAT", "id":"AF8_AR7"},
	    {"label":"GTCGCTAG_CCATGCGC", "id":"AF8_AR8"},
	    {"label":"GTCGCTAG_CCGCTAGG", "id":"AF8_AR9"},
	    {"label":"GTCGCTAG_CGCATCAT", "id":"AF8_AR10"},
	    {"label":"GTCGCTAG_GAGGAGTA", "id":"AF8_AR11"},
	    {"label":"GTCGCTAG_GCTGGTCA", "id":"AF8_AR12"},
	    {"label":"GTCGCTAG_GGAGGCTC", "id":"AF8_AR13"},
	    {"label":"GTCGCTAG_GTAAGAAG", "id":"AF8_AR14"},
	    {"label":"GTCGCTAG_GTTAAGTT", "id":"AF8_AR15"},
	    {"label":"GTCGCTAG_TCGTTCGA", "id":"AF8_AR16"},
	    {"label":"GTCGCTAG_TGAATGGC", "id":"AF8_AR17"},
	    {"label":"GTCGCTAG_TGATCTCA", "id":"AF8_AR18"},
	    {"label":"GTCGCTAG_TGGTCCTG", "id":"AF8_AR19"},
	    {"label":"GTCGCTAG_TGGTTGAC", "id":"AF8_AR20"},
	    {"label":"TGGTTGAC_AACCAACG", "id":"AF9_AR1"},
	    {"label":"TGGTTGAC_AACCGAAC", "id":"AF9_AR2"},
	    {"label":"TGGTTGAC_ACTGCTCT", "id":"AF9_AR3"},
	    {"label":"TGGTTGAC_ATACCAGG", "id":"AF9_AR4"},
	    {"label":"TGGTTGAC_ATTGATTA", "id":"AF9_AR5"},
	    {"label":"TGGTTGAC_CAACCTCT", "id":"AF9_AR6"},
	    {"label":"TGGTTGAC_CAGAATAT", "id":"AF9_AR7"},
	    {"label":"TGGTTGAC_CCATGCGC", "id":"AF9_AR8"},
	    {"label":"TGGTTGAC_CCGCTAGG", "id":"AF9_AR9"},
	    {"label":"TGGTTGAC_CGCATCAT", "id":"AF9_AR10"},
	    {"label":"TGGTTGAC_GAGGAGTA", "id":"AF9_AR11"},
	    {"label":"TGGTTGAC_GCTGGTCA", "id":"AF9_AR12"},
	    {"label":"TGGTTGAC_GGAGGCTC", "id":"AF9_AR13"},
	    {"label":"TGGTTGAC_GTAAGAAG", "id":"AF9_AR14"},
	    {"label":"TGGTTGAC_GTTAAGTT", "id":"AF9_AR15"},
	    {"label":"TGGTTGAC_TCGTTCGA", "id":"AF9_AR16"},
	    {"label":"TGGTTGAC_TGAATGGC", "id":"AF9_AR17"},
	    {"label":"TGGTTGAC_TGATCTCA", "id":"AF9_AR18"},
	    {"label":"TGGTTGAC_TGGTCCTG", "id":"AF9_AR19"},
	    {"label":"TGGTTGAC_TGGTTGAC", "id":"AF9_AR20"},
	    {"label":"TTAGATCG_AACCAACG", "id":"AF10_AR1"},
	    {"label":"TTAGATCG_AACCGAAC", "id":"AF10_AR2"},
	    {"label":"TTAGATCG_ACTGCTCT", "id":"AF10_AR3"},
	    {"label":"TTAGATCG_ATACCAGG", "id":"AF10_AR4"},
	    {"label":"TTAGATCG_ATTGATTA", "id":"AF10_AR5"},
	    {"label":"TTAGATCG_CAACCTCT", "id":"AF10_AR6"},
	    {"label":"TTAGATCG_CAGAATAT", "id":"AF10_AR7"},
	    {"label":"TTAGATCG_CCATGCGC", "id":"AF10_AR8"},
	    {"label":"TTAGATCG_CCGCTAGG", "id":"AF10_AR9"},
	    {"label":"TTAGATCG_CGCATCAT", "id":"AF10_AR10"},
	    {"label":"TTAGATCG_GAGGAGTA", "id":"AF10_AR11"},
	    {"label":"TTAGATCG_GCTGGTCA", "id":"AF10_AR12"},
	    {"label":"TTAGATCG_GGAGGCTC", "id":"AF10_AR13"},
	    {"label":"TTAGATCG_GTAAGAAG", "id":"AF10_AR14"},
	    {"label":"TTAGATCG_GTTAAGTT", "id":"AF10_AR15"},
	    {"label":"TTAGATCG_TCGTTCGA", "id":"AF10_AR16"},
	    {"label":"TTAGATCG_TGAATGGC", "id":"AF10_AR17"},
	    {"label":"TTAGATCG_TGATCTCA", "id":"AF10_AR18"},
	    {"label":"TTAGATCG_TGGTCCTG", "id":"AF10_AR19"},
	    {"label":"TTAGATCG_TGGTTGAC", "id":"AF10_AR20"}
	];
	
	$indexNameList = [
	    {"id":"ATCACG", "label":"Index_1"},
	    {"id":"CGATGT", "label":"Index_2"},
	    {"id":"TTAGGC", "label":"Index_3"},
	    {"id":"TGACCA", "label":"Index_4"},
	    {"id":"ACAGTG", "label":"Index_5"},
	    {"id":"GCCAAT", "label":"Index_6"},
	    {"id":"CAGATC", "label":"Index_7"},
	    {"id":"ACTTGA", "label":"Index_8"},
	    {"id":"GATCAG", "label":"Index_9"},
	    {"id":"TAGCTT", "label":"Index_10"},
	    {"id":"GGCTAC", "label":"Index_11"},
	    {"id":"CTTGTA", "label":"Index_12"},
	    {"id":"CGTAGT", "label":"Cap_index_1"},
	    {"id":"CAGCAC", "label":"Cap_index_2"},
	    {"id":"ACTGCG", "label":"Cap_index_3"},
	    {"id":"TCGATG", "label":"Cap_index_4"},
	    {"id":"TACGAG", "label":"Cap_index_5"},
	    {"id":"GTCGTC", "label":"Cap_index_6"},
	    {"id":"GCTACT", "label":"Cap_index_7"},
	    {"id":"GAGTAG", "label":"Cap_index_8"},
	    {"id":"AGTGAG", "label":"Cap_index_9"},
	    {"id":"ACAGAG", "label":"Cap_index_10"},
	    {"id":"CTCTGC", "label":"Cap_index_11"},
	    {"id":"TAGCTG", "label":"Cap_index_12"},
	    {"id":"CTATCA", "label":"Custom_13"},
	    {"id":"CGTATA", "label":"Custom_14"},
	    {"id":"TGATCG", "label":"Custom_15"},
	    {"id":"GTGTAT", "label":"Custom_16"},
	    {"id":"CGCTAT", "label":"Custom_17"},
	    {"id":"TGAACA", "label":"Custom_18"},
	    {"id":"GTATCT", "label":"Custom_19"},
	    {"id":"CAGCTA", "label":"Custom_20"},
	    {"id":"ACATAC", "label":"Custom_21"},
	    {"id":"TGAGCC", "label":"Custom_22"},
	    {"id":"AGCATG", "label":"Custom_23"},
	    {"id":"CGATGA", "label":"Custom_24"},
	    {"id":"TAGATG", "label":"Custom_25"},
	    {"id":"TGTGAC", "label":"Custom_26"},
	    {"id":"TGCATA", "label":"Custom_27"},
	    {"id":"TCTCGC", "label":"Custom_28"},
	    {"id":"TGATGC", "label":"Custom_29"},
	    {"id":"GACGAC", "label":"Custom_30"},
	    {"id":"GACACT", "label":"Custom_31"},
	    {"id":"ACGCAT", "label":"Custom_32"},
	    {"id":"GACCGG", "label":"Custom_33"},
	    {"id":"GAGATA", "label":"Custom_34"},
	    {"id":"CTGACA", "label":"Custom_35"},
	    {"id":"TGCAGG", "label":"Custom_36"},
	    {"id":"ACTGCC", "label":"Custom_37"},
	    {"id":"GCAACG", "label":"Custom_38"},
	    {"id":"CGACCT", "label":"Custom_39"},
	    {"id":"TGACGT", "label":"Custom_40"},
	    {"id":"TGTCTG", "label":"Custom_41"},
	    {"id":"ACGTGC", "label":"Custom_42"},
	    {"id":"TGATCC", "label":"Custom_43"},
	    {"id":"CTCTAG", "label":"Custom_44"},
	    {"id":"GAGAAG", "label":"Custom_45"},
	    {"id":"CACGAA", "label":"Custom_46"},
	    {"id":"CATAGA", "label":"Custom_47"},
	    {"id":"ACAGTC", "label":"Custom_48"},
	    {"id":"CATCGT", "label":"Custom_49"},
	    {"id":"TTGAAC", "label":"Custom_50"},
	    {"id":"ACGTCG", "label":"Custom_51"},
	    {"id":"ATCACG", "label":"TruSeq_1"},
	    {"id":"CGATGT", "label":"TruSeq_2"},
	    {"id":"TTAGGC", "label":"TruSeq_3"},
	    {"id":"TGACCA", "label":"TruSeq_4"},
	    {"id":"ACAGTG", "label":"TruSeq_5"},
	    {"id":"GCCAAT", "label":"TruSeq_6"},
	    {"id":"CAGATC", "label":"TruSeq_7"},
	    {"id":"ACTTGA", "label":"TruSeq_8"},
	    {"id":"GATCAG", "label":"TruSeq_9"},
	    {"id":"TAGCTT", "label":"TruSeq_10"},
	    {"id":"GGCTAC", "label":"TruSeq_11"},
	    {"id":"CTTGTA", "label":"TruSeq_12"},
	    {"id":"AGTCAA", "label":"TruSeq_13"},
	    {"id":"AGTTCC", "label":"TruSeq_14"},
	    {"id":"ATGTCA", "label":"TruSeq_15"},
	    {"id":"CCGTCC", "label":"TruSeq_16"},
	    {"id":"GTAGAG", "label":"TruSeq_17"},
	    {"id":"GTCCGC", "label":"TruSeq_18"},
	    {"id":"GTGAAA", "label":"TruSeq_19"},
	    {"id":"GTGGCC", "label":"TruSeq_20"},
	    {"id":"GTTTCG", "label":"TruSeq_21"},
	    {"id":"CGTACG", "label":"TruSeq_22"},
	    {"id":"GAGTGG", "label":"TruSeq_23"},
	    {"id":"GGTAGC", "label":"TruSeq_24"},
	    {"id":"ACTGAT", "label":"TruSeq_25"},
	    {"id":"ATGAGC", "label":"TruSeq_26"},
	    {"id":"ATTCCT", "label":"TruSeq_27"},
	    {"id":"CAAAAG", "label":"TruSeq_28"},
	    {"id":"CAACTA", "label":"TruSeq_29"},
	    {"id":"CACCGG", "label":"TruSeq_30"},
	    {"id":"CACGAT", "label":"TruSeq_31"},
	    {"id":"CACTCA", "label":"TruSeq_32"},
	    {"id":"CAGGCG", "label":"TruSeq_33"},
	    {"id":"CATGGC", "label":"TruSeq_34"},
	    {"id":"CATTTT", "label":"TruSeq_35"},
	    {"id":"CCAACA", "label":"TruSeq_36"},
	    {"id":"CGGAAT", "label":"TruSeq_37"},
	    {"id":"CTAGCT", "label":"TruSeq_38"},
	    {"id":"CTATAC", "label":"TruSeq_39"},
	    {"id":"CTCAGA", "label":"TruSeq_40"},
	    {"id":"GACGAC", "label":"TruSeq_41"},
	    {"id":"TAATCG", "label":"TruSeq_42"},
	    {"id":"TACAGC", "label":"TruSeq_43"},
	    {"id":"TATAAT", "label":"TruSeq_44"},
	    {"id":"TCATTC", "label":"TruSeq_45"},
	    {"id":"TCCCGA", "label":"TruSeq_46"},
	    {"id":"TCGAAG", "label":"TruSeq_47"},
	    {"id":"TCGGCA", "label":"TruSeq_48"},
	    {"id":"ATCACG", "label":"NEBNext_1"},
	    {"id":"CGATGT", "label":"NEBNext_2"},
	    {"id":"TTAGGC", "label":"NEBNext_3"},
	    {"id":"TGACCA", "label":"NEBNext_4"},
	    {"id":"ACAGTG", "label":"NEBNext_5"},
	    {"id":"GCCAAT", "label":"NEBNext_6"},
	    {"id":"CAGATC", "label":"NEBNext_7"},
	    {"id":"ACTTGA", "label":"NEBNext_8"},
	    {"id":"GATCAG", "label":"NEBNext_9"},
	    {"id":"TAGCTT", "label":"NEBNext_10"},
	    {"id":"GGCTAC", "label":"NEBNext_11"},
	    {"id":"CTTGTA", "label":"NEBNext_12"},
	    {"id":"ATCACG", "label":"AD001"},
	    {"id":"CGATGT", "label":"AD002"},
	    {"id":"TTAGGC", "label":"AD003"},
	    {"id":"TGACCA", "label":"AD004"},
	    {"id":"ACAGTG", "label":"AD005"},
	    {"id":"GCCAAT", "label":"AD006"},
	    {"id":"CAGATC", "label":"AD007"},
	    {"id":"ACTTGA", "label":"AD008"},
	    {"id":"GATCAG", "label":"AD009"},
	    {"id":"TAGCTT", "label":"AD010"},
	    {"id":"GGCTAC", "label":"AD011"},
	    {"id":"CTTGTA", "label":"AD012"},
	    {"id":"AGTCAA", "label":"AD013"},
	    {"id":"AGTTCC", "label":"AD014"},
	    {"id":"ATGTCA", "label":"AD015"},
	    {"id":"CCGTCC", "label":"AD016"},
	    {"id":"GTCCGC", "label":"AD018"},
	    {"id":"GTGAAA", "label":"AD019"},
	    {"id":"GTGGCC", "label":"AD020"},
	    {"id":"GTTTCG", "label":"AD021"},
	    {"id":"CGTACG", "label":"AD022"},
	    {"id":"GAGTGG", "label":"AD023"},
	    {"id":"ACTGAT", "label":"AD025"},
	    {"id":"ATTCCT", "label":"AD027"},
	    {"id":"TCATCG", "label":"Custom_24rev"},
	    {"id":"ACGTCA", "label":"Custom_40rev"},
	    {"id":"CAGGCC", "label":"SB_33"},
	    {"id":"AAGGGA", "label":"L2V6DR_BC1"},
	    {"id":"CCTTCA", "label":"L2V6DR_BC2"},
	    {"id":"GGACCC", "label":"L2V6DR_BC3"},
	    {"id":"TTCAGC", "label":"L2V6DR_BC4"},
	    {"id":"TAAGGCGA_TAGATCGC", "label":"N701_S501"},
	    {"id":"TAAGGCGA_CTCTCTAT", "label":"N701_S502"},
	    {"id":"TAAGGCGA_TATCCTCT", "label":"N701_S503"},
	    {"id":"TAAGGCGA_AGAGTAGA", "label":"N701_S504"},
	    {"id":"TAAGGCGA_GTAAGGAG", "label":"N701_S505"},
	    {"id":"TAAGGCGA_ACTGCATA", "label":"N701_S506"},
	    {"id":"TAAGGCGA_AAGGAGTA", "label":"N701_S507"},
	    {"id":"TAAGGCGA_CTAAGCCT", "label":"N701_S508"},
	    {"id":"CGTACTAG_TAGATCGC", "label":"N702_S501"},
	    {"id":"CGTACTAG_CTCTCTAT", "label":"N702_S502"},
	    {"id":"CGTACTAG_TATCCTCT", "label":"N702_S503"},
	    {"id":"CGTACTAG_AGAGTAGA", "label":"N702_S504"},
	    {"id":"CGTACTAG_GTAAGGAG", "label":"N702_S505"},
	    {"id":"CGTACTAG_ACTGCATA", "label":"N702_S506"},
	    {"id":"CGTACTAG_AAGGAGTA", "label":"N702_S507"},
	    {"id":"CGTACTAG_CTAAGCCT", "label":"N702_S508"},
	    {"id":"AGGCAGAA_TAGATCGC", "label":"N703_S501"},
	    {"id":"AGGCAGAA_CTCTCTAT", "label":"N703_S502"},
	    {"id":"AGGCAGAA_TATCCTCT", "label":"N703_S503"},
	    {"id":"AGGCAGAA_AGAGTAGA", "label":"N703_S504"},
	    {"id":"AGGCAGAA_GTAAGGAG", "label":"N703_S505"},
	    {"id":"AGGCAGAA_ACTGCATA", "label":"N703_S506"},
	    {"id":"AGGCAGAA_AAGGAGTA", "label":"N703_S507"},
	    {"id":"AGGCAGAA_CTAAGCCT", "label":"N703_S508"},
	    {"id":"TCCTGAGC_TAGATCGC", "label":"N704_S501"},
	    {"id":"TCCTGAGC_CTCTCTAT", "label":"N704_S502"},
	    {"id":"TCCTGAGC_TATCCTCT", "label":"N704_S503"},
	    {"id":"TCCTGAGC_AGAGTAGA", "label":"N704_S504"},
	    {"id":"TCCTGAGC_GTAAGGAG", "label":"N704_S505"},
	    {"id":"TCCTGAGC_ACTGCATA", "label":"N704_S506"},
	    {"id":"TCCTGAGC_AAGGAGTA", "label":"N704_S507"},
	    {"id":"TCCTGAGC_CTAAGCCT", "label":"N704_S508"},
	    {"id":"GGACTCCT_TAGATCGC", "label":"N705_S501"},
	    {"id":"GGACTCCT_CTCTCTAT", "label":"N705_S502"},
	    {"id":"GGACTCCT_TATCCTCT", "label":"N705_S503"},
	    {"id":"GGACTCCT_AGAGTAGA", "label":"N705_S504"},
	    {"id":"GGACTCCT_GTAAGGAG", "label":"N705_S505"},
	    {"id":"GGACTCCT_ACTGCATA", "label":"N705_S506"},
	    {"id":"GGACTCCT_AAGGAGTA", "label":"N705_S507"},
	    {"id":"GGACTCCT_CTAAGCCT", "label":"N705_S508"},
	    {"id":"TAGGCATG_TAGATCGC", "label":"N706_S501"},
	    {"id":"TAGGCATG_CTCTCTAT", "label":"N706_S502"},
	    {"id":"TAGGCATG_TATCCTCT", "label":"N706_S503"},
	    {"id":"TAGGCATG_AGAGTAGA", "label":"N706_S504"},
	    {"id":"TAGGCATG_GTAAGGAG", "label":"N706_S505"},
	    {"id":"TAGGCATG_ACTGCATA", "label":"N706_S506"},
	    {"id":"TAGGCATG_AAGGAGTA", "label":"N706_S507"},
	    {"id":"TAGGCATG_CTAAGCCT", "label":"N706_S508"},
	    {"id":"CTCTCTAC_TAGATCGC", "label":"N707_S501"},
	    {"id":"CTCTCTAC_CTCTCTAT", "label":"N707_S502"},
	    {"id":"CTCTCTAC_TATCCTCT", "label":"N707_S503"},
	    {"id":"CTCTCTAC_AGAGTAGA", "label":"N707_S504"},
	    {"id":"CTCTCTAC_GTAAGGAG", "label":"N707_S505"},
	    {"id":"CTCTCTAC_ACTGCATA", "label":"N707_S506"},
	    {"id":"CTCTCTAC_AAGGAGTA", "label":"N707_S507"},
	    {"id":"CTCTCTAC_CTAAGCCT", "label":"N707_S508"},
	    {"id":"CAGAGAGG_TAGATCGC", "label":"N708_S501"},
	    {"id":"CAGAGAGG_CTCTCTAT", "label":"N708_S502"},
	    {"id":"CAGAGAGG_TATCCTCT", "label":"N708_S503"},
	    {"id":"CAGAGAGG_AGAGTAGA", "label":"N708_S504"},
	    {"id":"CAGAGAGG_GTAAGGAG", "label":"N708_S505"},
	    {"id":"CAGAGAGG_ACTGCATA", "label":"N708_S506"},
	    {"id":"CAGAGAGG_AAGGAGTA", "label":"N708_S507"},
	    {"id":"CAGAGAGG_CTAAGCCT", "label":"N708_S508"},
	    {"id":"GCTACGCT_TAGATCGC", "label":"N709_S501"},
	    {"id":"GCTACGCT_CTCTCTAT", "label":"N709_S502"},
	    {"id":"GCTACGCT_TATCCTCT", "label":"N709_S503"},
	    {"id":"GCTACGCT_AGAGTAGA", "label":"N709_S504"},
	    {"id":"GCTACGCT_GTAAGGAG", "label":"N709_S505"},
	    {"id":"GCTACGCT_ACTGCATA", "label":"N709_S506"},
	    {"id":"GCTACGCT_AAGGAGTA", "label":"N709_S507"},
	    {"id":"GCTACGCT_CTAAGCCT", "label":"N709_S508"},
	    {"id":"CGAGGCTG_TAGATCGC", "label":"N710_S501"},
	    {"id":"CGAGGCTG_CTCTCTAT", "label":"N710_S502"},
	    {"id":"CGAGGCTG_TATCCTCT", "label":"N710_S503"},
	    {"id":"CGAGGCTG_AGAGTAGA", "label":"N710_S504"},
	    {"id":"CGAGGCTG_GTAAGGAG", "label":"N710_S505"},
	    {"id":"CGAGGCTG_ACTGCATA", "label":"N710_S506"},
	    {"id":"CGAGGCTG_AAGGAGTA", "label":"N710_S507"},
	    {"id":"CGAGGCTG_CTAAGCCT", "label":"N710_S508"},
	    {"id":"AAGAGGCA_TAGATCGC", "label":"N711_S501"},
	    {"id":"AAGAGGCA_CTCTCTAT", "label":"N711_S502"},
	    {"id":"AAGAGGCA_TATCCTCT", "label":"N711_S503"},
	    {"id":"AAGAGGCA_AGAGTAGA", "label":"N711_S504"},
	    {"id":"AAGAGGCA_GTAAGGAG", "label":"N711_S505"},
	    {"id":"AAGAGGCA_ACTGCATA", "label":"N711_S506"},
	    {"id":"AAGAGGCA_AAGGAGTA", "label":"N711_S507"},
	    {"id":"AAGAGGCA_CTAAGCCT", "label":"N711_S508"},
	    {"id":"GTAGAGGA_TAGATCGC", "label":"N712_S501"},
	    {"id":"GTAGAGGA_CTCTCTAT", "label":"N712_S502"},
	    {"id":"GTAGAGGA_TATCCTCT", "label":"N712_S503"},
	    {"id":"GTAGAGGA_AGAGTAGA", "label":"N712_S504"},
	    {"id":"GTAGAGGA_GTAAGGAG", "label":"N712_S505"},
	    {"id":"GTAGAGGA_ACTGCATA", "label":"N712_S506"},
	    {"id":"GTAGAGGA_AAGGAGTA", "label":"N712_S507"},
	    {"id":"GTAGAGGA_CTAAGCCT", "label":"N712_S508"},
	    {"id":"AACCAACG_AACCAACG", "label":"AF1_AR1"},
	    {"id":"AACCAACG_AACCGAAC", "label":"AF1_AR2"},
	    {"id":"AACCAACG_ACTGCTCT", "label":"AF1_AR3"},
	    {"id":"AACCAACG_ATACCAGG", "label":"AF1_AR4"},
	    {"id":"AACCAACG_ATTGATTA", "label":"AF1_AR5"},
	    {"id":"AACCAACG_CAACCTCT", "label":"AF1_AR6"},
	    {"id":"AACCAACG_CAGAATAT", "label":"AF1_AR7"},
	    {"id":"AACCAACG_CCATGCGC", "label":"AF1_AR8"},
	    {"id":"AACCAACG_CCGCTAGG", "label":"AF1_AR9"},
	    {"id":"AACCAACG_CGCATCAT", "label":"AF1_AR10"},
	    {"id":"AACCAACG_GAGGAGTA", "label":"AF1_AR11"},
	    {"id":"AACCAACG_GCTGGTCA", "label":"AF1_AR12"},
	    {"id":"AACCAACG_GGAGGCTC", "label":"AF1_AR13"},
	    {"id":"AACCAACG_GTAAGAAG", "label":"AF1_AR14"},
	    {"id":"AACCAACG_GTTAAGTT", "label":"AF1_AR15"},
	    {"id":"AACCAACG_TCGTTCGA", "label":"AF1_AR16"},
	    {"id":"AACCAACG_TGAATGGC", "label":"AF1_AR17"},
	    {"id":"AACCAACG_TGATCTCA", "label":"AF1_AR18"},
	    {"id":"AACCAACG_TGGTCCTG", "label":"AF1_AR19"},
	    {"id":"AACCAACG_TGGTTGAC", "label":"AF1_AR20"},
	    {"id":"AAGAGCTC_AACCAACG", "label":"AF2_AR1"},
	    {"id":"AAGAGCTC_AACCGAAC", "label":"AF2_AR2"},
	    {"id":"AAGAGCTC_ACTGCTCT", "label":"AF2_AR3"},
	    {"id":"AAGAGCTC_ATACCAGG", "label":"AF2_AR4"},
	    {"id":"AAGAGCTC_ATTGATTA", "label":"AF2_AR5"},
	    {"id":"AAGAGCTC_CAACCTCT", "label":"AF2_AR6"},
	    {"id":"AAGAGCTC_CAGAATAT", "label":"AF2_AR7"},
	    {"id":"AAGAGCTC_CCATGCGC", "label":"AF2_AR8"},
	    {"id":"AAGAGCTC_CCGCTAGG", "label":"AF2_AR9"},
	    {"id":"AAGAGCTC_CGCATCAT", "label":"AF2_AR10"},
	    {"id":"AAGAGCTC_GAGGAGTA", "label":"AF2_AR11"},
	    {"id":"AAGAGCTC_GCTGGTCA", "label":"AF2_AR12"},
	    {"id":"AAGAGCTC_GGAGGCTC", "label":"AF2_AR13"},
	    {"id":"AAGAGCTC_GTAAGAAG", "label":"AF2_AR14"},
	    {"id":"AAGAGCTC_GTTAAGTT", "label":"AF2_AR15"},
	    {"id":"AAGAGCTC_TCGTTCGA", "label":"AF2_AR16"},
	    {"id":"AAGAGCTC_TGAATGGC", "label":"AF2_AR17"},
	    {"id":"AAGAGCTC_TGATCTCA", "label":"AF2_AR18"},
	    {"id":"AAGAGCTC_TGGTCCTG", "label":"AF2_AR19"},
	    {"id":"AAGAGCTC_TGGTTGAC", "label":"AF2_AR20"},
	    {"id":"AGATAAGT_AACCAACG", "label":"AF3_AR1"},
	    {"id":"AGATAAGT_AACCGAAC", "label":"AF3_AR2"},
	    {"id":"AGATAAGT_ACTGCTCT", "label":"AF3_AR3"},
	    {"id":"AGATAAGT_ATACCAGG", "label":"AF3_AR4"},
	    {"id":"AGATAAGT_ATTGATTA", "label":"AF3_AR5"},
	    {"id":"AGATAAGT_CAACCTCT", "label":"AF3_AR6"},
	    {"id":"AGATAAGT_CAGAATAT", "label":"AF3_AR7"},
	    {"id":"AGATAAGT_CCATGCGC", "label":"AF3_AR8"},
	    {"id":"AGATAAGT_CCGCTAGG", "label":"AF3_AR9"},
	    {"id":"AGATAAGT_CGCATCAT", "label":"AF3_AR10"},
	    {"id":"AGATAAGT_GAGGAGTA", "label":"AF3_AR11"},
	    {"id":"AGATAAGT_GCTGGTCA", "label":"AF3_AR12"},
	    {"id":"AGATAAGT_GGAGGCTC", "label":"AF3_AR13"},
	    {"id":"AGATAAGT_GTAAGAAG", "label":"AF3_AR14"},
	    {"id":"AGATAAGT_GTTAAGTT", "label":"AF3_AR15"},
	    {"id":"AGATAAGT_TCGTTCGA", "label":"AF3_AR16"},
	    {"id":"AGATAAGT_TGAATGGC", "label":"AF3_AR17"},
	    {"id":"AGATAAGT_TGATCTCA", "label":"AF3_AR18"},
	    {"id":"AGATAAGT_TGGTCCTG", "label":"AF3_AR19"},
	    {"id":"AGATAAGT_TGGTTGAC", "label":"AF3_AR20"},
	    {"id":"CAACCATC_AACCAACG", "label":"AF4_AR1"},
	    {"id":"CAACCATC_AACCGAAC", "label":"AF4_AR2"},
	    {"id":"CAACCATC_ACTGCTCT", "label":"AF4_AR3"},
	    {"id":"CAACCATC_ATACCAGG", "label":"AF4_AR4"},
	    {"id":"CAACCATC_ATTGATTA", "label":"AF4_AR5"},
	    {"id":"CAACCATC_CAACCTCT", "label":"AF4_AR6"},
	    {"id":"CAACCATC_CAGAATAT", "label":"AF4_AR7"},
	    {"id":"CAACCATC_CCATGCGC", "label":"AF4_AR8"},
	    {"id":"CAACCATC_CCGCTAGG", "label":"AF4_AR9"},
	    {"id":"CAACCATC_CGCATCAT", "label":"AF4_AR10"},
	    {"id":"CAACCATC_GAGGAGTA", "label":"AF4_AR11"},
	    {"id":"CAACCATC_GCTGGTCA", "label":"AF4_AR12"},
	    {"id":"CAACCATC_GGAGGCTC", "label":"AF4_AR13"},
	    {"id":"CAACCATC_GTAAGAAG", "label":"AF4_AR14"},
	    {"id":"CAACCATC_GTTAAGTT", "label":"AF4_AR15"},
	    {"id":"CAACCATC_TCGTTCGA", "label":"AF4_AR16"},
	    {"id":"CAACCATC_TGAATGGC", "label":"AF4_AR17"},
	    {"id":"CAACCATC_TGATCTCA", "label":"AF4_AR18"},
	    {"id":"CAACCATC_TGGTCCTG", "label":"AF4_AR19"},
	    {"id":"CAACCATC_TGGTTGAC", "label":"AF4_AR20"},
	    {"id":"CCTAGCGA_AACCAACG", "label":"AF5_AR1"},
	    {"id":"CCTAGCGA_AACCGAAC", "label":"AF5_AR2"},
	    {"id":"CCTAGCGA_ACTGCTCT", "label":"AF5_AR3"},
	    {"id":"CCTAGCGA_ATACCAGG", "label":"AF5_AR4"},
	    {"id":"CCTAGCGA_ATTGATTA", "label":"AF5_AR5"},
	    {"id":"CCTAGCGA_CAACCTCT", "label":"AF5_AR6"},
	    {"id":"CCTAGCGA_CAGAATAT", "label":"AF5_AR7"},
	    {"id":"CCTAGCGA_CCATGCGC", "label":"AF5_AR8"},
	    {"id":"CCTAGCGA_CCGCTAGG", "label":"AF5_AR9"},
	    {"id":"CCTAGCGA_CGCATCAT", "label":"AF5_AR10"},
	    {"id":"CCTAGCGA_GAGGAGTA", "label":"AF5_AR11"},
	    {"id":"CCTAGCGA_GCTGGTCA", "label":"AF5_AR12"},
	    {"id":"CCTAGCGA_GGAGGCTC", "label":"AF5_AR13"},
	    {"id":"CCTAGCGA_GTAAGAAG", "label":"AF5_AR14"},
	    {"id":"CCTAGCGA_GTTAAGTT", "label":"AF5_AR15"},
	    {"id":"CCTAGCGA_TCGTTCGA", "label":"AF5_AR16"},
	    {"id":"CCTAGCGA_TGAATGGC", "label":"AF5_AR17"},
	    {"id":"CCTAGCGA_TGATCTCA", "label":"AF5_AR18"},
	    {"id":"CCTAGCGA_TGGTCCTG", "label":"AF5_AR19"},
	    {"id":"CCTAGCGA_TGGTTGAC", "label":"AF5_AR20"},
	    {"id":"GCTCTGCT_AACCAACG", "label":"AF6_AR1"},
	    {"id":"GCTCTGCT_AACCGAAC", "label":"AF6_AR2"},
	    {"id":"GCTCTGCT_ACTGCTCT", "label":"AF6_AR3"},
	    {"id":"GCTCTGCT_ATACCAGG", "label":"AF6_AR4"},
	    {"id":"GCTCTGCT_ATTGATTA", "label":"AF6_AR5"},
	    {"id":"GCTCTGCT_CAACCTCT", "label":"AF6_AR6"},
	    {"id":"GCTCTGCT_CAGAATAT", "label":"AF6_AR7"},
	    {"id":"GCTCTGCT_CCATGCGC", "label":"AF6_AR8"},
	    {"id":"GCTCTGCT_CCGCTAGG", "label":"AF6_AR9"},
	    {"id":"GCTCTGCT_CGCATCAT", "label":"AF6_AR10"},
	    {"id":"GCTCTGCT_GAGGAGTA", "label":"AF6_AR11"},
	    {"id":"GCTCTGCT_GCTGGTCA", "label":"AF6_AR12"},
	    {"id":"GCTCTGCT_GGAGGCTC", "label":"AF6_AR13"},
	    {"id":"GCTCTGCT_GTAAGAAG", "label":"AF6_AR14"},
	    {"id":"GCTCTGCT_GTTAAGTT", "label":"AF6_AR15"},
	    {"id":"GCTCTGCT_TCGTTCGA", "label":"AF6_AR16"},
	    {"id":"GCTCTGCT_TGAATGGC", "label":"AF6_AR17"},
	    {"id":"GCTCTGCT_TGATCTCA", "label":"AF6_AR18"},
	    {"id":"GCTCTGCT_TGGTCCTG", "label":"AF6_AR19"},
	    {"id":"GCTCTGCT_TGGTTGAC", "label":"AF6_AR20"},
	    {"id":"GGCGTTGC_AACCAACG", "label":"AF7_AR1"},
	    {"id":"GGCGTTGC_AACCGAAC", "label":"AF7_AR2"},
	    {"id":"GGCGTTGC_ACTGCTCT", "label":"AF7_AR3"},
	    {"id":"GGCGTTGC_ATACCAGG", "label":"AF7_AR4"},
	    {"id":"GGCGTTGC_ATTGATTA", "label":"AF7_AR5"},
	    {"id":"GGCGTTGC_CAACCTCT", "label":"AF7_AR6"},
	    {"id":"GGCGTTGC_CAGAATAT", "label":"AF7_AR7"},
	    {"id":"GGCGTTGC_CCATGCGC", "label":"AF7_AR8"},
	    {"id":"GGCGTTGC_CCGCTAGG", "label":"AF7_AR9"},
	    {"id":"GGCGTTGC_CGCATCAT", "label":"AF7_AR10"},
	    {"id":"GGCGTTGC_GAGGAGTA", "label":"AF7_AR11"},
	    {"id":"GGCGTTGC_GCTGGTCA", "label":"AF7_AR12"},
	    {"id":"GGCGTTGC_GGAGGCTC", "label":"AF7_AR13"},
	    {"id":"GGCGTTGC_GTAAGAAG", "label":"AF7_AR14"},
	    {"id":"GGCGTTGC_GTTAAGTT", "label":"AF7_AR15"},
	    {"id":"GGCGTTGC_TCGTTCGA", "label":"AF7_AR16"},
	    {"id":"GGCGTTGC_TGAATGGC", "label":"AF7_AR17"},
	    {"id":"GGCGTTGC_TGATCTCA", "label":"AF7_AR18"},
	    {"id":"GGCGTTGC_TGGTCCTG", "label":"AF7_AR19"},
	    {"id":"GGCGTTGC_TGGTTGAC", "label":"AF7_AR20"},
	    {"id":"GTCGCTAG_AACCAACG", "label":"AF8_AR1"},
	    {"id":"GTCGCTAG_AACCGAAC", "label":"AF8_AR2"},
	    {"id":"GTCGCTAG_ACTGCTCT", "label":"AF8_AR3"},
	    {"id":"GTCGCTAG_ATACCAGG", "label":"AF8_AR4"},
	    {"id":"GTCGCTAG_ATTGATTA", "label":"AF8_AR5"},
	    {"id":"GTCGCTAG_CAACCTCT", "label":"AF8_AR6"},
	    {"id":"GTCGCTAG_CAGAATAT", "label":"AF8_AR7"},
	    {"id":"GTCGCTAG_CCATGCGC", "label":"AF8_AR8"},
	    {"id":"GTCGCTAG_CCGCTAGG", "label":"AF8_AR9"},
	    {"id":"GTCGCTAG_CGCATCAT", "label":"AF8_AR10"},
	    {"id":"GTCGCTAG_GAGGAGTA", "label":"AF8_AR11"},
	    {"id":"GTCGCTAG_GCTGGTCA", "label":"AF8_AR12"},
	    {"id":"GTCGCTAG_GGAGGCTC", "label":"AF8_AR13"},
	    {"id":"GTCGCTAG_GTAAGAAG", "label":"AF8_AR14"},
	    {"id":"GTCGCTAG_GTTAAGTT", "label":"AF8_AR15"},
	    {"id":"GTCGCTAG_TCGTTCGA", "label":"AF8_AR16"},
	    {"id":"GTCGCTAG_TGAATGGC", "label":"AF8_AR17"},
	    {"id":"GTCGCTAG_TGATCTCA", "label":"AF8_AR18"},
	    {"id":"GTCGCTAG_TGGTCCTG", "label":"AF8_AR19"},
	    {"id":"GTCGCTAG_TGGTTGAC", "label":"AF8_AR20"},
	    {"id":"TGGTTGAC_AACCAACG", "label":"AF9_AR1"},
	    {"id":"TGGTTGAC_AACCGAAC", "label":"AF9_AR2"},
	    {"id":"TGGTTGAC_ACTGCTCT", "label":"AF9_AR3"},
	    {"id":"TGGTTGAC_ATACCAGG", "label":"AF9_AR4"},
	    {"id":"TGGTTGAC_ATTGATTA", "label":"AF9_AR5"},
	    {"id":"TGGTTGAC_CAACCTCT", "label":"AF9_AR6"},
	    {"id":"TGGTTGAC_CAGAATAT", "label":"AF9_AR7"},
	    {"id":"TGGTTGAC_CCATGCGC", "label":"AF9_AR8"},
	    {"id":"TGGTTGAC_CCGCTAGG", "label":"AF9_AR9"},
	    {"id":"TGGTTGAC_CGCATCAT", "label":"AF9_AR10"},
	    {"id":"TGGTTGAC_GAGGAGTA", "label":"AF9_AR11"},
	    {"id":"TGGTTGAC_GCTGGTCA", "label":"AF9_AR12"},
	    {"id":"TGGTTGAC_GGAGGCTC", "label":"AF9_AR13"},
	    {"id":"TGGTTGAC_GTAAGAAG", "label":"AF9_AR14"},
	    {"id":"TGGTTGAC_GTTAAGTT", "label":"AF9_AR15"},
	    {"id":"TGGTTGAC_TCGTTCGA", "label":"AF9_AR16"},
	    {"id":"TGGTTGAC_TGAATGGC", "label":"AF9_AR17"},
	    {"id":"TGGTTGAC_TGATCTCA", "label":"AF9_AR18"},
	    {"id":"TGGTTGAC_TGGTCCTG", "label":"AF9_AR19"},
	    {"id":"TGGTTGAC_TGGTTGAC", "label":"AF9_AR20"},
	    {"id":"TTAGATCG_AACCAACG", "label":"AF10_AR1"},
	    {"id":"TTAGATCG_AACCGAAC", "label":"AF10_AR2"},
	    {"id":"TTAGATCG_ACTGCTCT", "label":"AF10_AR3"},
	    {"id":"TTAGATCG_ATACCAGG", "label":"AF10_AR4"},
	    {"id":"TTAGATCG_ATTGATTA", "label":"AF10_AR5"},
	    {"id":"TTAGATCG_CAACCTCT", "label":"AF10_AR6"},
	    {"id":"TTAGATCG_CAGAATAT", "label":"AF10_AR7"},
	    {"id":"TTAGATCG_CCATGCGC", "label":"AF10_AR8"},
	    {"id":"TTAGATCG_CCGCTAGG", "label":"AF10_AR9"},
	    {"id":"TTAGATCG_CGCATCAT", "label":"AF10_AR10"},
	    {"id":"TTAGATCG_GAGGAGTA", "label":"AF10_AR11"},
	    {"id":"TTAGATCG_GCTGGTCA", "label":"AF10_AR12"},
	    {"id":"TTAGATCG_GGAGGCTC", "label":"AF10_AR13"},
	    {"id":"TTAGATCG_GTAAGAAG", "label":"AF10_AR14"},
	    {"id":"TTAGATCG_GTTAAGTT", "label":"AF10_AR15"},
	    {"id":"TTAGATCG_TCGTTCGA", "label":"AF10_AR16"},
	    {"id":"TTAGATCG_TGAATGGC", "label":"AF10_AR17"},
	    {"id":"TTAGATCG_TGATCTCA", "label":"AF10_AR18"},
	    {"id":"TTAGATCG_TGGTCCTG", "label":"AF10_AR19"},
	    {"id":"TTAGATCG_TGGTTGAC", "label":"AF10_AR20"}
	];
	
	$refgenomeList = ["hg19","hg18","mm9","mm10","rn5","rn4","dm3","ce6","ce10","sacCer3"]
	$speciesList = ["human","mouse","rat"]
	$cellTypeList = ["ESC","E14","NPC","Fibroblast","LSK","NB4","HL60"]
	$IPList = ["IgG"]
	$TOEList = ["ChiP","DIP","RNA","shRNA","Exome","Genome"]
	
//wiki Links
	var dateLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_date";
	var BilltoLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_billto";
	var LPLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_labperson";
	var BPLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_bioperson";
	var PILink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_pi";
	var addInfoLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_addinfo";
	var runtypeLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_runtype";
	var phixLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_phix";
	var seqLibLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_seqLib";
	var leftoversLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_leftovers";
	var custSeqLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_custSeq";
	var concentrationUnitLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_concentration_unit";

	var tubeTagLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_tubetag";
	var simpleIdLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_sampleid";
	var concentrationLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_concentration";
	var averageLibLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_averageLib";
	var indexSeqLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_indexSeq";
	var indexNameLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_indexName";
	var projectNameLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_projectName";
	
	var refGenomeLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_refGenome";
	var speciesLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_species";
	var cellTypeLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_cellType";
	var ipLink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_ip";
	var TOELink = "http://wiki.dna.ku.dk/dokuwiki/doku.php?id=orderform_typeofexperiment";

//Error msg:
	var labPNerr = "Lab person name must be filled out";
	var labPMerr = "Lab person mail must be filled out or not a valid email";
	var labPPerr = "Lab person phone must be filled out";
	var bioPNerr = "Bioinformatics person name must be filled out";
	var bioPMerr = "Bioinformatics person mail must be filled out or not a valid email";
	var pierr = "You havn't select any PI";
	var billToerr = "Bill To must be filled out";
	var CVROrEANerr = "Need to specify either CVR or EAN information.";
	var interr = "Have to specify a number";
	var doublerr = "Have to specify a number";
	var runtypeerr = "Need to specify one runtype";
	// err msg for numberbetween is in validate.js file!
